# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage
# cache: cocoapods
# podfile: Example/Podfile

#os: osx
#osx_image: xcode10.3
#language: swift
#before_install:
#- gem install cocoapods # Since Travis is not always on latest version
#- pod install --project-directory=Example
#script:
#- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/myCustomTestCharly.xcworkspace -scheme myCustomTestCharly-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
#- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/myCustomTestCharly.xcworkspace -scheme myCustomTestCharly-Example -destination \"platform=iOS Simulator,name=iPhone 8\" | xcpretty
#- pod lib lint

language: swift
osx_image: xcode10
xcode_sdk: iphonesimulator12.0
script:
- set -o pipefail
- travis_retry xcodebuild -workspace Example/myCustomTestCharly.xcworkspace -scheme myCustomTestCharly-Example -destination "platform=iOS Simulator,name=iPhone 6" build-for-testing test | xcpretty
